### ISSUE TITLE
Will the source code be made available?

### ISSUE THREAD

**Issue by rpetit3** [raja-appuswamy/accel-align-release#1]

**Comment by raja-appuswamy** [comment]
Hello Robert. Thank you very much for your interest. As we were focusing on getting the manuscript ready, we rushed with the code. We are now working on refactoring it and cleaning it up. We will definitely make the source code available in the near future. In the meantime, if there's some functionality you would need, let me know. We can add it quickly and push an updated binary. We are also open to collaboration. So please do not hesitate to get in touch directly via email for further discussion.

**Comment by raja-appuswamy** [comment]
Hello Robert. We have now made the source code available in the repo. Please let us know if you have any problems.
