### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by pdimens** [raja-appuswamy/accel-align-release#15]
Hello, I'm very excited to try out accel-align in my research! I would like to be able to cite versioned releases in the subsequent work but there are no tagged releases of this software. Given that the manuscript has been published, may you please begin tagging versioned releases, as this would help data transparency and reproducibility using this aligner?

Thank you,

Pavel

**Comment by raja-appuswamy** [comment]
Hello Pavel,
  Thank you for reaching out. We are super excited that you are interested in Accel-Align, and look forward to getting feedback from you as you use it. In fact, we are in the process of pushing an important update within the next couple days which should provide substantial improvement in accuracy. We are absolutely going to start making tagged, versioned releases. I'll keep this issue open and comment back again when we are done tagging our next release.

Regards,
Raja

**Comment by raja-appuswamy** [comment]
Hello Pavel,
  As promised, we have started tagging releases and we will continue to do so. So i'm closing this issue. As an aside, our new release should provide better accuracy at the same performance. So i hope you test it out and find it useful. Please do not hesitate to get in touch if you need any help/have any comments.

Regards
Raja
