### ISSUE TITLE
embedding question

### ISSUE THREAD

**Issue by fmughal** [raja-appuswamy/accel-align-release#18]
Hello Raja,

Is there an option to disable embedding in accel-align (similar to the demonstration in the publication) or would that require changes to the source code prior to compilation?

Thanks,
-Fizza

**Comment by yanlolo** [comment]
Hey Fizza,

Disable embedding will make the aligner super slow so we do not support an option to disable embedding publicly. We only did that to illustrate the impact of embedding. If you have a special requirement to used a mode without embedding, please let us know. 

Regards,
Yiqing

**Comment by fmughal** [comment]
Thank you, Yiqing. Yes, I'd like to try out accel-align without embedding (and of course, with embedding using the software out-of-the-box). The little bit of boost in accuracy at the cost of speed according to the accel-align paper, is of particular interest to me.

**Comment by fmughal** [comment]
Hello, I was hoping to follow up on my request for access to the accel-align no-embedding version. Thank you.

**Comment by yanlolo** [comment]
Hey Fizza,

I have added the option to disable embedding (extend all candidates) today. This mode could be enabled by '-d'. Please pull the last commit and try.  

Example:

```
path-to-code/accel-align-release/accalign -l 32 -t $threads -d -o $output/accalign.sam \
    path-to-ref/hg37.fna $input/$r1
```

**Comment by fmughal** [comment]
Thank you, Yiqing!
