### ISSUE TITLE
Common features

### ISSUE THREAD

**Issue by slw287r** [raja-appuswamy/accel-align-release#2]
Hi Raja,

Thanks for your excellent aligner, it's faster (10× or more) and has a significant lower memory footprint compared to bwa, bwa-mem2 and sentieon.
While some common features are still missing such as `NM:i:#` and isizes. `samtools fixmate` adds in the isize and the `=` convention for the same contig but are still lacking some common tags. Looking forward to a more general-feature-completed and speed-remained version.

Cheers,
Richard

**Comment by raja-appuswamy** [comment]
Hello Richard,
  Very glad to hear that you find the aligner useful and fast. Thank you very much for your feedback. We are definitely working on adding the missing features. I'll post an update as soon as we have a new version ready so that you can test it out.

Regards,
Raja

**Comment by raja-appuswamy** [comment]
Hello Richard,
 The latest version of the aligner should have the features you requested. So i am closing this issue. Please feel free to open it again if you find something missing.

Raja
