### ISSUE TITLE
Sorting BAM issue

### ISSUE THREAD

**Issue by ksahlin** [raja-appuswamy/accel-align-release#22]
Hi Team,

I've yet to rerun v1.1 on all my previous benchmarks, but I have now run accecalign v1.1 on two simulated and two biological datasets for variant calling. Accelalign finishes on all four datasets, but on two of them (the two biological datasets) downstream sorting fails. The downstream sorting step completes without errors for the simulated data though. Errors shown below.

SIM150
```
[W::sam_parse1] unrecognized reference name ""; treated as unmapped
[W::sam_parse1] unrecognized mate reference name "HISEQ1:47:HA66FADXX:2:1212:12631:9"...; treated as unmapped
samtools view: error reading file "/proj/snic2022-6-31/nobackup/strobealign_eval/alignments_PE/accelalign/BIO150.sam": Input/output error
samtools view: error closing "/proj/snic2022-6-31/nobackup/strobealign_eval/alignments_PE/accelalign/BIO150.sam": -5
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
```

SIM250
```
[W::sam_parse1] unrecognized reference name ""; treated as unmapped
[W::sam_parse1] unrecognized mate reference name "HISEQ1:93:H2YHMBCXX:1:1103:7133:10"...; treated as unmapped
samtools view: error reading file "/proj/snic2022-6-31/nobackup/strobealign_eval/alignments_PE/accelalign/BIO250.sam": No such file or directory
samtools view: error closing "/proj/snic2022-6-31/nobackup/strobealign_eval/alignments_PE/accelalign/BIO250.sam": -5
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
```

The command for producing this
```
samtools view -@ 16 -u accelalign.sam | samtools sort -@ 16 -o accelalign.bam'
```

Please see details on the two biological datasets in the analysis described [here](https://github.com/ksahlin/StrobeAlign#variant-calling-benchmark-giab).

**Comment by yanlolo** [comment]
Hey Kristoffer,

Thank you very much for reporting the error. 

We pushed a new commit and updated the binary file accalign-x86-64. We tested 250bp D3_S1_L001_R* reads in https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG004_NA24143_mother/NIST_Illumina_2x250bps/reads/ and no error reported. Could you please pull new commit and help to try again? Please let us know if the error still exists. Thanks.

Regards,
Yiqing

**Comment by ksahlin** [comment]
Started pipeline. I will get back to you about it when the jobs are complete (currently long waiting times on starting jobs on the server).

**Comment by ksahlin** [comment]
The new commit fixed the errors I reported. Thanks!
